# Generated by Django 5.2.6 on 2025-09-30 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='심볼')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('exchange', models.CharField(max_length=50, verbose_name='거래소')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '주식 심볼',
                'verbose_name_plural': '주식 심볼들',
                'ordering': ['category', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='날짜시간')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='저가')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocksymbol', verbose_name='심볼')),
            ],
            options={
                'verbose_name': '주식 데이터',
                'verbose_name_plural': '주식 데이터들',
                'ordering': ['-datetime'],
                'unique_together': {('symbol', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocksymbol', verbose_name='심볼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '관심종목',
                'verbose_name_plural': '관심종목들',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
